(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ca=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},da=ca(this),g=function(a,b){if(b)a:{var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}};
g("Symbol",function(a){if(a)return a;var b=function(f,h){this.g=f;ba(this,"description",{configurable:!0,writable:!0,value:h})};b.prototype.toString=function(){return this.g};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(f||"")+"_"+d++,f)};return e});
g("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=da[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ea(aa(this))}})}return a});
var ea=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},fa="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},ha;if("function"==typeof Object.setPrototypeOf)ha=Object.setPrototypeOf;else{var ia;a:{var ja={a:!0},ka={};try{ka.__proto__=ja;ia=ka.a;break a}catch(a){}ia=!1}ha=ia?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var la=ha,ma=function(a,b){a.prototype=fa(b.prototype);a.prototype.constructor=a;if(la)la(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.G=b.prototype},na=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};
g("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(l){return l};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var h=0;!(f=b.next()).done;)e.push(c.call(d,f.value,h++))}else for(f=b.length,h=0;h<f;h++)e.push(c.call(d,b[h],h));return e}});g("Array.prototype.values",function(a){return a?a:function(){return na(this,function(b,c){return c})}});
var oa="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)Object.prototype.hasOwnProperty.call(d,e)&&(a[e]=d[e])}return a};g("Object.assign",function(a){return a||oa});g("globalThis",function(a){return a||da});g("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&c.push(b[d]);return c}});
var k=this||self,pa=function(a){"object"!=typeof a||a&&Array.isArray(a)},qa=function(a){return a};var n,q;a:{for(var ra=["CLOSURE_FLAGS"],r=k,sa=0;sa<ra.length;sa++)if(r=r[ra[sa]],null==r){q=null;break a}q=r}var ta=q&&q[610401301];n=null!=ta?ta:!1;function t(){var a=k.navigator;return a&&(a=a.userAgent)?a:""}var u,ua=k.navigator;u=ua?ua.userAgentData||null:null;function va(a){return n?u?u.brands.some(function(b){return(b=b.brand)&&-1!=b.indexOf(a)}):!1:!1}function v(a){return-1!=t().indexOf(a)};function w(){return n?!!u&&0<u.brands.length:!1}function wa(){return w()?!1:v("Opera")}function xa(){return v("Firefox")||v("FxiOS")}function ya(){return w()?va("Chromium"):(v("Chrome")||v("CriOS"))&&!(w()?0:v("Edge"))||v("Silk")};function x(){return n?!!u&&!!u.platform:!1}function za(){return v("iPhone")&&!v("iPod")&&!v("iPad")}function Aa(){za()||v("iPad")||v("iPod")};var Ba=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1};wa();var Ca=w()?!1:v("Trident")||v("MSIE");v("Edge");!v("Gecko")||-1!=t().toLowerCase().indexOf("webkit")&&!v("Edge")||v("Trident")||v("MSIE")||v("Edge");-1!=t().toLowerCase().indexOf("webkit")&&!v("Edge")&&v("Mobile");x()||v("Macintosh");x()||v("Windows");(x()?"Linux"===u.platform:v("Linux"))||x()||v("CrOS");var Da=k.navigator||null;Da&&(Da.appVersion||"").indexOf("X11");x()||v("Android");za();v("iPad");v("iPod");Aa();t().toLowerCase().indexOf("kaios");xa();za()||v("iPod");v("iPad");!v("Android")||ya()||xa()||wa()||v("Silk");ya();!v("Safari")||ya()||(w()?0:v("Coast"))||wa()||(w()?0:v("Edge"))||(w()?va("Microsoft Edge"):v("Edg/"))||(w()?va("Opera"):v("OPR"))||xa()||v("Silk")||v("Android")||Aa();var Ea={},y=null;var Fa="undefined"!==typeof Uint8Array,Ga=!Ca&&"function"===typeof btoa;var z="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol():void 0;function A(a,b){if(z)return a[z]|=b;if(void 0!==a.g)return a.g|=b;Object.defineProperties(a,{g:{value:b,configurable:!0,writable:!0,enumerable:!1}});return b}function Ha(a){var b=B(a);1!==(b&1)&&(Object.isFrozen(a)&&(a=Array.prototype.slice.call(a)),C(a,b|1))}function B(a){var b;z?b=a[z]:b=a.g;return null==b?0:b}
function C(a,b){z?a[z]=b:void 0!==a.g?a.g=b:Object.defineProperties(a,{g:{value:b,configurable:!0,writable:!0,enumerable:!1}});return a}function Ia(){var a=[];A(a,1);return a}function Ja(a,b){C(b,(a|0)&-51)}function Ka(a,b){C(b,(a|18)&-41)};var La={};function D(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}var Ma,E=Object.freeze(C([],23));var F=function(a,b,c){if(B(a.h)&2)throw Error();return Na(a,b,c)},Na=function(a,b,c){a.A&&(a.A=void 0);if(b>=a.g){var d=a.g+a.o;(a.s||(a.s=a.h[d]={}))[b]=c;return a}a.h[b+a.o]=c;(c=a.s)&&b in c&&delete c[b];return a};var G;function Oa(a,b){return Pa(b)}
function Pa(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "boolean":return a?1:0;case "object":if(a&&!Array.isArray(a)&&Fa&&null!=a&&a instanceof Uint8Array){if(Ga){for(var b="",c=0,d=a.length-10240;c<d;)b+=String.fromCharCode.apply(null,a.subarray(c,c+=10240));b+=String.fromCharCode.apply(null,c?a.subarray(c):a);a=btoa(b)}else{void 0===b&&(b=0);if(!y){y={};c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split("");d=["+/=","+/","-_=","-_.","-_"];for(var e=
0;5>e;e++){var f=c.concat(d[e].split(""));Ea[e]=f;for(var h=0;h<f.length;h++){var l=f[h];void 0===y[l]&&(y[l]=h)}}}b=Ea[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(e=f=0;f<a.length-2;f+=3){var p=a[f],m=a[f+1];l=a[f+2];h=b[p>>2];p=b[(p&3)<<4|m>>4];m=b[(m&15)<<2|l>>6];l=b[l&63];c[e++]=h+p+m+l}h=0;l=d;switch(a.length-f){case 2:h=a[f+1],l=b[(h&15)<<2]||d;case 1:a=a[f],c[e]=b[a>>2]+b[(a&3)<<4|h>>4]+l+d}a=c.join("")}return a}}return a};function Qa(a,b){for(var c=Array.prototype.slice.call(a.h),d=a.s,e=c.length+(d?-1:0),f=0;f<e;f++)c[f]=b(c[f]);if(d){e=c[f]={};for(var h in d)e[h]=b(d[h])}b=a.constructor;A(c,16);G=c;c=new b(c);G=void 0;a.u&&(c.u=a.u.slice());return c}function Ra(a,b,c,d,e,f){if(null!=a){if(Array.isArray(a))a=e&&0==a.length&&B(a)&1?void 0:f&&B(a)&2?a:Sa(a,b,c,void 0!==d,e,f);else if(D(a)){var h={},l;for(l in a)h[l]=Ra(a[l],b,c,d,e,f);a=h}else a=b(a,d);return a}}
function Sa(a,b,c,d,e,f){var h=d||c?B(a):0;d=d?!!(h&16):void 0;a=Array.prototype.slice.call(a);for(var l=0;l<a.length;l++)a[l]=Ra(a[l],b,c,d,e,f);c&&c(h,a);return a}function Ta(a){return a.v===La?a.toJSON():Pa(a)};function Ua(a,b,c){c=void 0===c?Ka:c;if(null!=a){if(Fa&&a instanceof Uint8Array)return b?a:new Uint8Array(a);if(Array.isArray(a)){var d=B(a);if(d&2)return a;if(b&&!(d&32)&&(d&16||0===d))return C(a,d|18),a;a=Sa(a,Ua,d&4?Ka:c,!0,!1,!0);b=B(a);b&4&&b&2&&Object.freeze(a);return a}a.v===La&&(B(a.h)&2||(a=Va(a,!0),A(a.h,18)));return a}}function Va(a,b){var c=b||B(a.h)&2?Ka:Ja,d=!!(B(a.h)&16);return Qa(a,function(e){return Ua(e,d,c)})};var H=function(a,b,c){null==a&&(a=G);G=void 0;if(null==a)a=c?[c]:[],C(a,48);else{if(!Array.isArray(a))throw Error();if(c&&c!==a[0])throw Error();var d=A(a,0)|32;C(a,d)}this.o=c?0:-1;this.h=a;a:{c=this.h.length;a=c-1;if(c&&(c=this.h[a],D(c))){this.s=c;this.g=a-this.o;break a}b?(this.g=Math.max(b,a+1-this.o),this.s=void 0):this.g=Number.MAX_VALUE}};H.prototype.toJSON=function(){if(Ma)var a=Wa(this,this.h,!1);else a=Sa(this.h,Ta,void 0,void 0,!1,!1),a=Wa(this,a,!0);return a};
H.prototype.clone=function(){return Va(this,!1)};H.prototype.v=La;H.prototype.toString=function(){return Wa(this,this.h,!1).toString()};
function Wa(a,b,c){var d=a?a.constructor.B:void 0,e=a.g;if(d){if(!c){b=Array.prototype.slice.call(b);var f;if(b.length&&D(f=b[b.length-1]))for(var h=0;h<d.length;h++)if(d[h]>=e){Object.assign(b[b.length-1]={},f);break}}e=b;c=!c;f=a.g;var l;for(h=0;h<d.length;h++){var p=d[h];if(p<f){p+=a.o;var m=e[p];null==m?e[p]=c?E:Ia():c&&m!==E&&Ha(m)}else l||(m=void 0,e.length&&D(m=e[e.length-1])?l=m:e.push(l={})),m=l[p],null==l[p]?l[p]=c?E:Ia():c&&m!==E&&Ha(m)}}return b};var I,Xa=function(){if(void 0===I){var a=null,b=k.trustedTypes;if(b&&b.createPolicy){try{a=b.createPolicy("goog#html",{createHTML:qa,createScript:qa,createScriptURL:qa})}catch(c){k.console&&k.console.error(c.message)}I=a}else I=a}return I};var J=function(a){this.g=a};J.prototype.toString=function(){return this.g+""};var Ya={};var Za={},K=function(a){this.g=a};K.prototype.toString=function(){return this.g.toString()};/*

 SPDX-License-Identifier: Apache-2.0
*/
(function(){return""}).toString().indexOf("`");var bb=function(a,b){if(!$a()){var c=Math.random();if(c<b)return c=ab(),a[Math.floor(c*a.length)]}return null},ab=function(){if(!globalThis.crypto)return Math.random();try{var a=new Uint32Array(1);globalThis.crypto.getRandomValues(a);return a[0]/65536/65536}catch(b){return Math.random()}},$a=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){return Ba(["Google Web Preview","Mediapartners-Google","Google-Read-Aloud","Google-Adwords"],cb)||1E-4>Math.random()}),cb=function(a){return-1!=
t().indexOf(a)};var db=function(a){H.call(this,a)};ma(db,H);var eb=function(a){H.call(this,a)};ma(eb,H);
var fb=function(a,b){return F(a,2,b)},gb=function(a,b){return F(a,3,b)},hb=function(a,b){return F(a,4,b)},ib=function(a,b){return F(a,5,b)},jb=function(a,b){return F(a,9,b)},kb=function(a,b){if(B(a.h)&2)throw Error();if(null!=b){for(var c=!!b.length,d=0;d<b.length;d++){var e=b[d];c=c&&!(B(e.h)&2)}e=B(b);d=e|1;d=(c?d|8:d&-9)|4;d!=e&&(c=d,Object.isFrozen(b)&&(b=Array.prototype.slice.call(b)),C(b,c))}null==b&&(b=void 0);return Na(a,10,b)},lb=function(a,b){return F(a,11,null==b?b:!!b)},mb=function(a,
b){return F(a,1,b)},nb=function(a,b){return F(a,7,null==b?b:!!b)};eb.B=[10,6];var ob="platform platformVersion architecture model uaFullVersion bitness fullVersionList wow64".split(" ");function pb(){var a;return null!=(a=k.google_tag_data)?a:k.google_tag_data={}}function qb(){var a,b;return"function"===typeof(null==(a=k.navigator)?void 0:null==(b=a.userAgentData)?void 0:b.getHighEntropyValues)}
function rb(){if(!qb())return null;var a=pb();if(a.uach_promise)return a.uach_promise;var b=k.navigator.userAgentData.getHighEntropyValues(ob).then(function(c){null!=a.uach||(a.uach=c);return c});return a.uach_promise=b}
function sb(a){var b;return lb(kb(ib(fb(mb(hb(nb(jb(gb(new eb,a.architecture||""),a.bitness||""),a.mobile||!1),a.model||""),a.platform||""),a.platformVersion||""),a.uaFullVersion||""),(null==(b=a.fullVersionList)?void 0:b.map(function(c){var d=new db;d=F(d,1,c.brand);return F(d,2,c.version)}))||[]),a.wow64||!1)};var tb=function(a){try{for(var b=null;b!=a;b=a,a=a.parent)switch(a.location.protocol){case "https:":return!0;case "file:":return!0;case "http:":return!1}}catch(c){}return!0}(k)?"https:":"http:",ub={},vb=(ub[1]="A4A26Ymj79UVY7C7JGUS4BG1s7MdcDokAQf/RP0paks+RoTYbXHxceT/5L4iKcsleFCngi75YfNRGW2+SpVv1ggAAACLeyJvcmlnaW4iOiJodHRwczovL2dvb2dsZXRhZ3NlcnZpY2VzLmNvbTo0NDMiLCJmZWF0dXJlIjoiUHJpdmFjeVNhbmRib3hBZHNBUElzIiwiZXhwaXJ5IjoxNjk1MTY3OTk5LCJpc1N1YmRvbWFpbiI6dHJ1ZSwiaXNUaGlyZFBhcnR5Ijp0cnVlfQ==",ub);var L=[],M=function(a){this.id=a.id;this.i=a.i;this.j=a.j;L.push(this)},wb=new M({id:1,i:{l:"40004000",m:"40004001"},j:1}),N=new M({id:4,i:{l:"40004006",m:"40004007"},j:4}),xb=new M({id:5,i:{l:"40004008",m:"40004009"},j:4}),yb=new M({id:12,i:{l:"44752204",m:"44752205"},j:11}),zb=new M({id:13,i:{l:"44761098",C:"44761099",D:"44761100",F:"44761101"},j:12}),Ab=new M({id:14,i:{l:"44762123",m:"44762124"},j:13});function Bb(){var a={};a[wb.id]=.5;a[N.id]=.02;a[xb.id]=.001;a[yb.id]=.001;a[zb.id]=.001;a[Ab.id]=.05;return a}function Cb(){var a=Db,b=typeof a;if(("object"!=b||null==a)&&"function"!=b)return!1;if(b="undefined"!=typeof Symbol&&Symbol.iterator&&L[Symbol.iterator])b=b.call(L);else if("number"==typeof L.length)b={next:aa(L)};else throw Error(String(L)+" is not an iterable or ArrayLike");for(var c=b.next();!c.done;c=b.next())if(c=a[c.value.id],"number"!==typeof c||0>c||1<c)return!1;return!0};function Eb(a){return null===a?"null":void 0===a?"undefined":a};function Fb(){if(!k.dcmads.uach){var a=rb();a&&(k.dcmads.uachp=a.then(function(b){var c=k.dcmads;a:{b=sb(b);Ma=!0;try{var d=JSON.stringify(b.toJSON(),Oa);break a}finally{Ma=!1}d=void 0}c.uach=d}))}};try{k.dcmads=k.dcmads||{};k.dcmads.startTime=(new Date).getTime();var Gb=k.dcmads,O=k.dcmads.version,P={loader:284};if(O)if(P.experiment=O.experiment,96==O.number||"p"==O.number)P.number=96;else if(96==O.number||"c"==O.number)P.number=96;if(!P.number){var Hb=bb([96,96],0);P.experiment=!!Hb;P.number=Hb||96}Gb.version=P;var Ib=k.dcmads,Jb,Db=k.dcmads.expts,Q;Q=void 0===Q?Bb:Q;Jb=Cb()?Db:Q();Ib.expts=Jb;var Kb=k.dcmads,Lb;var Mb=k.dcmads;if(null!=Mb.eids)Lb=Mb.eids;else{var Nb=[],Ob=k.navigator;if(Ob.connection&&
Ob.connection.saveData){var Pb=bb(Object.values(N.i),Mb.expts[N.id]);Pb&&Nb.push(N.j+"|"+Pb)}Lb=Nb.join(",")}Kb.eids=Lb;k.dcmads.ots=vb;Fb();var Qb=new RegExp("4\\|"+N.i.m),Rb=k.dcmads.version,Sb=Rb.number,Tb="";Rb.experiment&&96==Sb&&(Tb="?rxp=96x96");var Ub="impl_v"+Sb+".js"+Tb,Vb=k.document,Wb=Vb.currentScript||Array.from(Vb.getElementsByTagName("script")).pop(),Xb=(0==(Wb&&Wb.src||"").indexOf("http:")?"http:":"https:")+"//www.googletagservices.com/dcm/"+Ub;if(Qb.test(k.dcmads.eids)){var Yb=k.document,
R,Zb=Xb,$b=Zb=Eb(Zb),ac=Xa(),bc=ac?ac.createScriptURL($b):$b;R=new J(bc,Ya);var S,T=Yb;T=void 0===T?document:T;S=T.createElement("script");var cc;R instanceof J&&R.constructor===J?cc=R.g:(pa(R),cc="type_error:TrustedResourceUrl");S.src=cc;var dc,ec,fc,gc=null==(fc=(ec=(S.ownerDocument&&S.ownerDocument.defaultView||window).document).querySelector)?void 0:fc.call(ec,"script[nonce]");(dc=gc?gc.nonce||gc.getAttribute("nonce")||"":"")&&S.setAttribute("nonce",dc);var U=Yb.getElementsByTagName("script")[0];
U&&U.parentNode&&U.parentNode.insertBefore(S,U)}else{var hc=k.document,V,ic='<script src="'+Xb+'">\x3c/script>',jc=ic=Eb(ic),kc=Xa(),lc=kc?kc.createHTML(jc):jc;V=new K(lc,Za);var mc=hc.write,nc;V instanceof K&&V.constructor===K?nc=V.g:(pa(V),nc="type_error:SafeHtml");mc.call(hc,nc)}}catch(a){if(.01>Math.random()){var oc="";try{var W,X=a,Y=X.toString();X.name&&-1==Y.indexOf(X.name)&&(Y+=": "+X.name);X.message&&-1==Y.indexOf(X.message)&&(Y+=": "+X.message);if(X.stack){var Z=X.stack,pc=Y;try{-1==Z.indexOf(pc)&&
(Z=pc+"\n"+Z);for(var qc;Z!=qc;)qc=Z,Z=Z.replace(RegExp("((https?:/..*/)[^/:]*:\\d+(?:.|\n)*)\\2"),"$1");Y=Z.replace(RegExp("\n *","g"),"\n")}catch(b){Y=pc}}W=Y;W=W.substring(0,1024);oc=encodeURIComponent(W)}catch(b){oc="extr"}var rc=k.dcmads.eids,sc=document.createElement("img");sc.src=tb+"//pagead2.googlesyndication.com/pagead/gen_204?id=dcmads-err&ver=284&context=554"+((rc?"&eids="+rc:"")+"&msg="+oc);(k.google_image_requests=k.google_image_requests||[]).push(sc)}};}).call(this);
