module.exports = {
    F2: {
        QualWeb: '',
        AChecker: '',
        Axe: '',
        Wave: 'heading_possible',
        a11ywatchLite: '',
        continuum: '',
    },
    F22: {
        QualWeb: 'QW-WCAG-T26',
        AChecker: 'aria_eventhandler_role_valid',
        Axe: '',
        Wave: 'event_handler',
        a11ywatchLite: '',
        continuum: '',
    },
    F24: {
        QualWeb: 'QW-WCAG-T31',
        AChecker: 'text_contrast_sufficient',
        Axe: '',
        Wave: 'contrast',
        a11ywatchLite: '',
        continuum: '',
    },
    F25: {
        QualWeb: '',
        AChecker: '',
        Axe: '',
        Wave: '',
        a11ywatchLite: '',
        continuum: '',
    },
    F3: {
        QualWeb: '',
        AChecker: 'style_background_decorative',
        Axe: '',
        Wave: '',
        a11ywatchLite: '',
        continuum: '',
    },
    F30: {
        QualWeb: '',
        AChecker: '',
        Axe: '',
        Wave: '',
        a11ywatchLite: '',
        continuum: '',
    },
    F32: {
        QualWeb: '',
        AChecker: 'text_whitespace_valid',
        Axe: '',
        Wave: '',
        a11ywatchLite: '',
        continuum: '',
    },
    F36: {
        QualWeb: '',
        AChecker: 'input_onchange_review',
        Axe: '',
        Wave: '',
        a11ywatchLite: '',
        continuum: '',
    },
    F37: {
        QualWeb: '',
        AChecker: '',
        Axe: '',
        Wave: '',
        a11ywatchLite: '',
        continuum: '',
    },
    F4: {
        QualWeb: '',
        AChecker: '',
        Axe: '',
        Wave: '',
        a11ywatchLite: '',
        continuum: '',
    },
    F42: {
        QualWeb: 'QW-WCAG-T26',
        AChecker: 'script_onclick_misuse',
        Axe: '',
        Wave: '',
        a11ywatchLite: '',
        continuum: '',
    },
    F44: {
        QualWeb: '',
        AChecker: '',
        Axe: 'tabindex',
        Wave: 'tabindex',
        a11ywatchLite: '',
        continuum: '',
    },
    F54: {
        QualWeb: '',
        AChecker: '',
        Axe: '',
        Wave: '',
        a11ywatchLite: 'WCAG2AA.Principle2.Guideline2_1.2_1_1.SCR20.MouseDown',
        continuum: '',
    },
    F55: {
        QualWeb: 'QW-WCAG-T24',
        AChecker: 'script_focus_blur_review',
        Axe: '',
        Wave: '',
        a11ywatchLite: '',
        continuum: '',
    },
    F65: {
        QualWeb: 'QW-ACT-R17',
        AChecker: 'img_alt_valid',
        Axe: 'image-alt',
        Wave: 'alt_missing',
        a11ywatchLite: 'WCAG2AA.Principle1.Guideline1_1.1_1_1.H37',
        continuum: 362,
    },
    F68: {
        QualWeb: 'QW-ACT-R16',
        AChecker: 'input_label_exists', //TODO: It might have other names too 'input_label_visible'
        Axe: 'label',
        Wave: 'label_missing',
        a11ywatchLite: 'WCAG2AA.Principle1.Guideline1_3.1_3_1.F68', // TODO: This is too 'WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.InputTel.Name', 'WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.InputSearch.Name'
        continuum: 338, // TODO: This is too '2440'
    },
    F73: {
        QualWeb: '',
        AChecker: '',
        Axe: 'link-in-text-block',
        Wave: '',
        a11ywatchLite: '',
        continuum: '',
    },
    F77: {
        QualWeb: 'QW-ACT-R18',
        AChecker: 'element_id_unique',
        Axe: 'duplicate-id',
        Wave: '',
        a11ywatchLite: 'WCAG2AA.Principle4.Guideline4_1.4_1_1.F77',
        continuum: 1352,
    },
    F78: {
        QualWeb: '',
        AChecker: 'style_focus_visible',
        Axe: '',
        Wave: '',
        a11ywatchLite: '',
        continuum: '',
    },
    F80: {
        QualWeb: 'QW-WCAG-T28',
        AChecker: '',
        Axe: '',
        Wave: '',
        a11ywatchLite: '',
        continuum: '',
    },
    F89: {
        QualWeb: 'QW-WCAG-T21',
        AChecker: 'a_text_purpose',
        Axe: 'link-name',
        Wave: 'alt_link_missing',
        a11ywatchLite: 'WCAG2AA.Principle1.Guideline1_1.1_1_1.H30.2',
        continuum: 1301,
    },
    F9: {
        QualWeb: '',
        AChecker: '',
        Axe: '',
        Wave: '',
        a11ywatchLite: '',
        continuum: '',
    },
    F91: {
        QualWeb: '',
        AChecker: 'table_headers_exists',
        Axe: '',
        Wave: '',
        a11ywatchLite: '',
        continuum: 375,
    },
    F94: {
        QualWeb: '',
        AChecker: 'style_viewport_resizable',
        Axe: '',
        Wave: '',
        a11ywatchLite: '',
        continuum: '',
    },
    F96: {
        QualWeb: 'QW-ACT-R30',
        AChecker: 'label_name_visible',
        Axe: '',
        Wave: '',
        a11ywatchLite: 'WCAG2AA.Principle2.Guideline2_5.2_5_3.F96',
        continuum: '',
    }
}