module.exports = {
    "RID": "F3",
    "CIA": "F30",
    "RIA": "F65",
    "RHP": "F2",
    "ASB": "F32",
    "RAS": "F42",
    "RHD": "F91",
    "CFC": "F24",
    "RAD": "F73",
    "CIF": "F80",
    "CPF": "F94",
    "ROA": "F78",
    "MTB": "F4",
    "CPT": "F25",
    "CTO": "F44",
    "CDP": "F54",
    "CBL": "F96",
    "RAI": "F89",
    "RFA": "F55",
    "CCB": "F9",
    "CCC": "F22",
    "CCI": "F36",
    "CCS": "F37",
    "RIN": "F68",
    "MDI": "F77"
}