var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(c){var f=0;return function(){return f<c.length?{done:!1,value:c[f++]}:{done:!0}}};$jscomp.arrayIterator=function(c){return{next:$jscomp.arrayIteratorImpl(c)}};$jscomp.makeIterator=function(c){var f="undefined"!=typeof Symbol&&Symbol.iterator&&c[Symbol.iterator];return f?f.call(c):$jscomp.arrayIterator(c)};$jscomp.arrayFromIterator=function(c){for(var f,l=[];!(f=c.next()).done;)l.push(f.value);return l};
$jscomp.arrayFromIterable=function(c){return c instanceof Array?c:$jscomp.arrayFromIterator($jscomp.makeIterator(c))};
(function(){function c(){0!==k.length&&(f(k),[].concat($jscomp.arrayFromIterable(k)).forEach(function(b){[].concat($jscomp.arrayFromIterable(b.querySelectorAll(".showcase-card-tab-card__badge-wrap[data-start-time]"))).forEach(function(a){var d=y(a.dataset.startTime,a.dataset.endTime);a.classList.add(d);"live"===d&&(b.querySelector(".tab__item--shop-live").classList.add("live-on"),a=z(a,".showcase-card-tab-card__full-bleed-wrap"),d=a.querySelector(".showcase-card-tab-card__product-cta .cta--watch-live"))&&
(d.classList.add("on"),a.setAttribute("href",d.dataset.liveLinkPath),a.setAttribute("aria-label",d.dataset.liveLinkTitle),a.setAttribute("an-la",d.dataset.liveAnLa),d.classList.contains("cta--icon")?a.setAttribute("target","_blank"):a.removeAttribute("target"))})}))}function f(b){for(var a={$jscomp$loop$prop$i$2:0};a.$jscomp$loop$prop$i$2<b.length;a={$jscomp$loop$prop$i$2:a.$jscomp$loop$prop$i$2},a.$jscomp$loop$prop$i$2++){var d=b[a.$jscomp$loop$prop$i$2].querySelector(".showcase-card-tab__inner--without-cta")?
!1:!0;n[a.$jscomp$loop$prop$i$2]=b[a.$jscomp$loop$prop$i$2].querySelector(".tab");h[a.$jscomp$loop$prop$i$2]=e(b[a.$jscomp$loop$prop$i$2]).find(".showcase-card-tab__card-items .showcase-card-tab-card__full-bleed-wrap");p[a.$jscomp$loop$prop$i$2]=e(b[a.$jscomp$loop$prop$i$2]).find(".showcase-card-tab__card-items .showcase-card-tab-card__full-bleed-wrap--video");q[a.$jscomp$loop$prop$i$2]=b[a.$jscomp$loop$prop$i$2].querySelectorAll(".showcase-card-tab-card__product-cta");t[a.$jscomp$loop$prop$i$2]=
b[a.$jscomp$loop$prop$i$2].querySelector(".popup-video");n[a.$jscomp$loop$prop$i$2]&&(r[a.$jscomp$loop$prop$i$2]=b[a.$jscomp$loop$prop$i$2].querySelectorAll(".tab__item"),u[a.$jscomp$loop$prop$i$2]=b[a.$jscomp$loop$prop$i$2].querySelector(".showcase-card-tab__card-wrap"),m[a.$jscomp$loop$prop$i$2]=0,g[a.$jscomp$loop$prop$i$2]=new Swiper(u[a.$jscomp$loop$prop$i$2],{autoHeight:!0,on:{slideChange:function(a){return function(){v(a.$jscomp$loop$prop$i$2,g[a.$jscomp$loop$prop$i$2].activeIndex)}}(a),slideChangeTransitionEnd:function(a){return function(){A.setLazyLoad();
w(a.$jscomp$loop$prop$i$2)}}(a)}}),w(a.$jscomp$loop$prop$i$2),l(a.$jscomp$loop$prop$i$2));d&&(B(a.$jscomp$loop$prop$i$2),C(a.$jscomp$loop$prop$i$2))}x(0)}function l(b){for(var a={$jscomp$loop$prop$j$4:0};a.$jscomp$loop$prop$j$4<r[b].length;a={$jscomp$loop$prop$j$4:a.$jscomp$loop$prop$j$4},a.$jscomp$loop$prop$j$4++)r[b][a.$jscomp$loop$prop$j$4].addEventListener("click",function(a){return function(){v(b,a.$jscomp$loop$prop$j$4)}}(a))}function B(b){h[b].target.forEach(function(a,d){var c=e(a).find(".showcase-card-tab-card__product-description-wrap");
e(a).on("mouseleave",function(){c.target[0].classList.add("showcase-card-tab-card__product-description-wrap--show");q[b][d].classList.add("showcase-card-tab-card__product-cta--leave");h[b].target[d].classList.remove("showcase-card--hover")});e(a).on("mouseenter",function(){h[b].target[d].classList.add("showcase-card--hover")});e(a).on("focus",function(){c.target[0].classList.add("showcase-card-tab-card__product-description-wrap--show");q[b][d].classList.add("showcase-card-tab-card__product-cta--leave");
h[b].target[d].classList.add("showcase-card--hover")});e(a).on("blur",function(){h[b].target[d].classList.remove("showcase-card--hover")})})}function C(b){p[b]&&p[b].target.forEach(function(a,c){a.addEventListener("click",function(){D.open(t[b],c,a)})})}function w(b){h[b].target.forEach(function(a){e(a).attr("tabindex","-1");e(a).attr("aria-hidden",!0)});e(k[b]).find(".swiper-slide-active .showcase-card-tab-card__full-bleed-wrap").target.forEach(function(a){"presentation"!==e(a).attr("role")&&"none"!==
e(a).attr("role")?(e(a).attr("tabindex","0"),e(a).attr("aria-hidden",!1)):(e(a).removeAttr("tabindex"),e(a).removeAttr("aria-hidden"))})}function v(b,a){m[b]!==a&&(m[b]=a);g[b].slideTo(m[b]);E.selectTab(n[b],g[b].activeIndex);x(b)}function x(b){6<g[b].slides[g[b].activeIndex].querySelector(".showcase-card-tab-inner-container").childElementCount?g[b].$el.addClass("showcase-card-tab__card-wrap--long"):g[b].$el.removeClass("showcase-card-tab__card-wrap--long")}var k=document.querySelectorAll(".showcase-card-tab"),
e=window.sg.common.$q,E=window.sg.common.tab,A=window.sg.common.lazyLoad,D=window.sg.common.popupVideo,z=window.sg.common.utils.closest,y=window.sg.common.utils.getTimeStatus,n=[],r=[],u=[],g=[],h=[],p=[],m=[],q=[],t=[];window.sg.components.showcaseCardTab={init:c,reInit:function(){f(k)}};e.ready(function(){return c()})})();