var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(d){var c=0;return function(){return c<d.length?{done:!1,value:d[c++]}:{done:!0}}};$jscomp.arrayIterator=function(d){return{next:$jscomp.arrayIteratorImpl(d)}};$jscomp.makeIterator=function(d){var c="undefined"!=typeof Symbol&&Symbol.iterator&&d[Symbol.iterator];return c?c.call(d):$jscomp.arrayIterator(d)};$jscomp.arrayFromIterator=function(d){for(var c,e=[];!(c=d.next()).done;)e.push(c.value);return e};
$jscomp.arrayFromIterable=function(d){return d instanceof Array?d:$jscomp.arrayFromIterator($jscomp.makeIterator(d))};
(function(){var d=window.sg.common.$q,c=function(a){this.els={el:a,headerWrapEl:a.querySelector(".key-feature-tab__header-wrap"),tabEl:a.querySelector(".tab"),containerEl:a.querySelector(".key-feature-tab__container"),slideEls:a.querySelectorAll(".key-feature-tab__slide"),innerWrapEls:a.querySelectorAll(".key-feature-tab__inner-wrap"),videoCtaEls:a.querySelectorAll(".key-feature-tab__cta--video"),popupVideoEl:a.querySelector(".popup-video")};this.lazyLoad=window.sg.common.lazyLoad;this.tab=window.sg.common.tab;
this.video=window.sg.common.video;this.popupVideo=window.sg.common.popupVideo;this.isVisible=window.sg.common.utils.isVisible;this.getCurrentDevice=window.sg.common.utils.getCurrentDevice;this.isKeyFeatureTabShow=!1;this.moveStartX=0;this.isMoving=!1;this.swiperJumpDirection="";this.isSwiperTransitionUse=!0;this.tabSelect=this.swiperMove=this.isSwiping=!1;this.applyVideoControlEvent=!0;this.isRtl=window.sg.common.utils.isRtl;this.init()};c.prototype.init=function(){c.instances.has(this.els.el)||(c.instances.set(this.els.el,
this),this.swiper=new Swiper(this.els.containerEl,{speed:500}),this.setAccessibility(),this.prepareInteraction(),this.setHeaderTextColor(0),this.bindEvents(),this.checkKeyFeatureTabShow(),this.setCarouselHeight())};c.prototype.checkKeyFeatureTabShow=function(){this.isVisible(this.els.el)&&!this.isKeyFeatureTabShow?(this.isKeyFeatureTabShow=!0,this.lazyLoad.setLazyLoad(),this.playVideo()):!this.isVisible(this.els.el)&&this.isKeyFeatureTabShow&&(this.isKeyFeatureTabShow=!1,this.pauseVideo())};c.prototype.playVideo=
function(){if(this.applyVideoControlEvent){var a=this.swiper.slides[this.swiper.activeIndex].querySelector(".key-feature-tab__background-wrap .video");a&&this.video.play(a);(a=this.swiper.slides[this.swiper.activeIndex].querySelector(".key-feature-tab__inner-wrap .video"))&&this.video.play(a)}};c.prototype.stopVideo=function(){if(this.applyVideoControlEvent){var a=this.swiper.slides[this.swiper.activeIndex].querySelector(".key-feature-tab__background-wrap .video video");a&&(a.pause(),a.currentTime=
0);if(a=this.swiper.slides[this.swiper.activeIndex].querySelector(".key-feature-tab__inner-wrap .video video"))a.pause(),a.currentTime=0}};c.prototype.pauseVideo=function(){if(this.applyVideoControlEvent){var a=this.swiper.slides[this.swiper.activeIndex].querySelector(".key-feature-tab__background-wrap .video video");a&&a.pause();(a=this.swiper.slides[this.swiper.activeIndex].querySelector(".key-feature-tab__inner-wrap .video video"))&&a.pause()}};c.prototype.setHeaderTextColor=function(){var a="",
b=this.els.innerWrapEls[this.swiper.activeIndex];this.els.headerWrapEl.classList.remove("text-color--black");this.els.headerWrapEl.classList.remove("text-color--white");this.els.headerWrapEl.classList.remove("text-shadow");b.classList.contains("text-color--black")?a="text-color--black":b.classList.contains("text-color--white")&&(a="text-color--white");this.els.headerWrapEl.classList.add(a);b.classList.contains("text-shadow")&&this.els.headerWrapEl.classList.add("text-shadow")};c.prototype.bindEvents=
function(){var a=this;this.els.tabEl.addEventListener("tabSelect",function(b){a.swiperMove?a.swiperMove=!1:(a.tab.setSelectDisabled(a.els.tabEl,!0),a.stopVideo(),a.tabSelect=!0,b.detail>a.swiper.activeIndex+1?(a.swiper.realPrevIndex=a.swiper.activeIndex,a.swiper.slides[b.detail].insertAdjacentElement("beforebegin",a.swiper.slides[a.swiper.activeIndex]),a.swiper.update(),a.isSwiperTransitionUse=!1,a.swiper.slideTo(b.detail-1,0),a.swiper.update(),a.isSwiperTransitionUse=!0,a.swiperJumpDirection="right"):
b.detail<a.swiper.activeIndex-1&&(a.swiper.realPrevIndex=a.swiper.activeIndex,a.swiper.slides[b.detail].insertAdjacentElement("afterend",a.swiper.slides[a.swiper.activeIndex]),a.swiper.update(),a.isSwiperTransitionUse=!1,a.swiper.slideTo(b.detail+1,0,!1),a.swiper.update(),a.isSwiperTransitionUse=!0,a.swiperJumpDirection="left"),a.swiper.slideTo(b.detail))});this.swiper.on("slideChange",function(){a.isSwiperTransitionUse&&(a.applyVideoControlEvent=!1,a.lazyLoad.setLazyLoad(),[].concat($jscomp.arrayFromIterable(a.els.slideEls)).forEach(function(a){a.classList.remove("key-feature-tab__slide--active-left-side");
a.classList.remove("key-feature-tab__slide--active-right-side")}),a.els.headerWrapEl.classList.add("key-feature-tab__header-wrap--interaction"),setTimeout(function(){a.els.headerWrapEl.classList.remove("key-feature-tab__header-wrap--interaction")},600),a.setHeaderTextColor(),a.tabSelect?a.tabSelect=!1:(a.swiperMove=!0,a.tab.selectTab(a.els.tabEl,a.swiper.activeIndex)))});this.swiper.on("slideChangeTransitionEnd",function(){a.isSwiperTransitionUse&&(a.lazyLoad.setLazyLoad(),a.applyVideoControlEvent=
!0,a.prepareInteraction(),"right"===a.swiperJumpDirection?(a.swiper.slides[a.swiper.realPrevIndex].insertAdjacentElement("beforebegin",a.swiper.slides[a.swiper.activeIndex-1]),a.swiper.update()):"left"===a.swiperJumpDirection&&(a.swiper.slides[a.swiper.realPrevIndex].insertAdjacentElement("afterend",a.swiper.slides[a.swiper.activeIndex+1]),a.swiper.update()),a.setAccessibility(),a.isSwiping&&"mobile"!==a.getCurrentDevice()||a.playVideo(),a.isSwiping=!1,a.swiperJumpDirection="",a.tab.setSelectDisabled(a.els.tabEl,
!1))});this.els.containerEl.addEventListener("mousedown",function(b){a.slideMoveStart(b)});this.els.containerEl.addEventListener("mousemove",function(b){a.slideMoving(b)});this.els.containerEl.addEventListener("mouseup",function(b){a.slideMoveEnd(b)});this.els.containerEl.addEventListener("touchstart",function(b){a.slideMoveStart(b)});this.els.containerEl.addEventListener("touchmove",function(b){a.slideMoving(b)});this.els.containerEl.addEventListener("touchend",function(b){a.slideMoveEnd(b)});[].concat($jscomp.arrayFromIterable(this.els.slideEls)).forEach(function(b){b.addEventListener("mouseenter",
function(){a.pauseVideo()});b.addEventListener("mouseleave",function(){a.playVideo()})});[].concat($jscomp.arrayFromIterable(this.els.innerWrapEls)).forEach(function(b){[].concat($jscomp.arrayFromIterable(b.querySelectorAll(".cta"))).forEach(function(b){b.addEventListener("focus",function(){a.pauseVideo()});b.addEventListener("focusout",function(){a.playVideo()})})});[].concat($jscomp.arrayFromIterable(this.els.videoCtaEls)).forEach(function(b,c){b.addEventListener("click",function(){a.applyVideoControlEvent=
!1;a.popupVideo.open(a.els.popupVideoEl,c,b)})});this.els.popupVideoEl&&this.els.popupVideoEl.addEventListener("popupVideoClose",function(){a.applyVideoControlEvent=!0});document.addEventListener("scroll",function(){a.checkKeyFeatureTabShow()});window.addEventListener("resize",function(){a.applyVideoControlEvent&&a.checkKeyFeatureTabShow();a.setCarouselHeight()});window.addEventListener("orientationchange",function(){a.applyVideoControlEvent&&a.checkKeyFeatureTabShow()})};c.prototype.slideMoveStart=
function(a){this.moveStartX=a.offsetX?a.offsetX:a.touches[0].pageX;this.isMoving=!0};c.prototype.slideMoving=function(a){if(this.isMoving){var b=(a.offsetX?a.offsetX:a.touches[0].pageX)-this.moveStartX;(-20>=b||20<=b)&&a.preventDefault()}};c.prototype.slideMoveEnd=function(a){a=(a.offsetX?a.offsetX:a.changedTouches[0].pageX)-this.moveStartX;this.isRtl()?50<=a&&!this.swiper.isEnd?(this.stopVideo(),this.isSwiping=!0,this.swiper.slideTo(this.swiper.activeIndex+1)):-50>=a&&!this.swiper.isBeginning&&(this.stopVideo(),
this.isSwiping=!0,this.swiper.slideTo(this.swiper.activeIndex-1)):-50>=a&&!this.swiper.isEnd?(this.stopVideo(),this.isSwiping=!0,this.swiper.slideTo(this.swiper.activeIndex+1)):50<=a&&!this.swiper.isBeginning&&(this.stopVideo(),this.isSwiping=!0,this.swiper.slideTo(this.swiper.activeIndex-1));this.moveStartX=0;this.isMoving=!1};c.prototype.prepareInteraction=function(){var a=this;[].concat($jscomp.arrayFromIterable(this.els.slideEls)).forEach(function(b,c){c<a.swiper.activeIndex?b.classList.add("key-feature-tab__slide--active-left-side"):
c>a.swiper.activeIndex&&b.classList.add("key-feature-tab__slide--active-right-side")})};c.prototype.setAccessibility=function(){var a=this;[].concat($jscomp.arrayFromIterable(this.swiper.slides)).forEach(function(b,c){c===a.swiper.activeIndex?(b.removeAttribute("aria-hidden"),[].concat($jscomp.arrayFromIterable(b.querySelectorAll(".cta"))).forEach(function(a){a.removeAttribute("tabindex");a.removeAttribute("aria-hidden")})):(b.setAttribute("aria-hidden","true"),[].concat($jscomp.arrayFromIterable(b.querySelectorAll(".cta"))).forEach(function(a){a.setAttribute("tabindex",
"-1");a.setAttribute("aria-hidden","true")}))})};c.prototype.setCarouselHeight=function(){if(1440>this.els.el.offsetWidth){var a=0;"desktop"===this.getCurrentDevice()?a=810*this.els.el.offsetWidth/1440:"mobile"===this.getCurrentDevice()&&(a=640*this.els.el.offsetWidth/360);[].concat($jscomp.arrayFromIterable(this.els.slideEls)).forEach(function(b){b.querySelector(".key-feature-tab__slide-inner").style.height=a+"px"})}else[].concat($jscomp.arrayFromIterable(this.els.slideEls)).forEach(function(a){a.querySelector(".key-feature-tab__slide-inner").removeAttribute("style")})};
c.instances=new WeakMap;var e={initAll:function(){[].concat($jscomp.arrayFromIterable(document.querySelectorAll(".key-feature-tab"))).forEach(function(a){c.instances.has(a)||new c(a)})}};window.sg.components.keyFeatureTab=e;d.ready(function(){return e.initAll()})})();