var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(c){var f=0;return function(){return f<c.length?{done:!1,value:c[f++]}:{done:!0}}};$jscomp.arrayIterator=function(c){return{next:$jscomp.arrayIteratorImpl(c)}};$jscomp.makeIterator=function(c){var f="undefined"!=typeof Symbol&&Symbol.iterator&&c[Symbol.iterator];return f?f.call(c):$jscomp.arrayIterator(c)};$jscomp.arrayFromIterator=function(c){for(var f,k=[];!(f=c.next()).done;)k.push(f.value);return k};
$jscomp.arrayFromIterable=function(c){return c instanceof Array?c:$jscomp.arrayFromIterator($jscomp.makeIterator(c))};
(function(){function c(){p.setLazyLoad();g(e.section).target.forEach(function(a){f(a)})}function f(a){d.instances.has(a)?d.instances.get(a).reInit():new d(a)}function k(a){if(a!==document&&!1===a.matches(e.section))return!1;var b=a===document?e.section:"";[].concat($jscomp.arrayFromIterable(a.querySelectorAll(b+' .video[data-video-embed\x3d"true"]'))).forEach(function(a){window.sg.common.video.reInit(a)});[].concat($jscomp.arrayFromIterable(a.querySelectorAll(b+" .image"))).forEach(function(a){window.sg.common.image.reInit(a)});
return!0}var q=window.sg.common.libs,g=window.sg.common.$q,h=window.sg.common.utils,l=window.sg.common.video,p=window.sg.common.lazyLoad,m=window.sg.common.constants.BREAKPOINTS,n=window.sg.common.utils.setMobileFocusLoop,r=window.sg.common.utils.removeMobileFocusLoop,e={section:".st-feature-benefit-full-bleed",sectionInner:".st-feature-benefit-full-bleed__wrap",btnWrap:".st-feature-benefit-full-bleed__cta",btn:".st-feature-benefit-full-bleed__cta .js-video-play, .js-showroom",pop:".st-feature-benefit-full-bleed__video",
video:"div.video",close:".st-feature-benefit-full-bleed__close",layerTypeVideo:"st-feature-benefit-full-bleed--video-layer",ctaButton:".cta[data-target-popup-id]"},d=function(a){var b=this;this.ele={section:g(a),window:g(window),sectionInner:null,btnWrap:null,btn:null,pop:null,ctaButton:null,loopFirst:null,loopEnd:null};this.setProperty();this.setMobileFocusLoop=this.isPc=null;this.event={focusLock:this.eventFocusLock.bind(this)};this.handler={clickCtaButton:function(a){var b=g(null);if("string"===
typeof a.target.dataset.targetPopupId){var c=a.target.dataset.targetPopupId.trim().replace("#","");""!==c&&(b=g("#"+c))}b.hasClass("pr-g-j2a-converter")?window.sg.components.prGj2aCover.openPopup(b.target[0],a.currentTarget):b.css({display:"block",overflow:"hidden"})},resize:function(){b.setVideoSize()}};d.instances.set(a,this);this.init()};d.prototype.setProperty=function(){var a=this;this.ele.sectionInner=this.ele.section.find(e.sectionInner);this.ele.btnWrap=this.ele.section.find(e.btnWrap);this.ele.btn=
this.ele.section.find(e.btn);this.ele.pop=this.ele.section.find(e.pop);this.ele.video=this.ele.pop.find(e.video).target[0];this.ele.close=this.ele.section.find(e.close);this.ele.ctaButton=this.ele.section.find(e.ctaButton);this.ele.LayerPopup=null;(this.contentVideo=this.ele.section.find(".st-feature-benefit-full-bleed__figure").hasClass("s-video-bg"))&&setTimeout(function(){var b=a.ele.section.find(".st-feature-benefit-full-bleed__figure.s-video-bg").find(e.video);"mp4"===b.attr("data-video-type")&&
JSON.parse(b.attr("data-video-data")).controls&&a.ele.section.find(".st-feature-benefit-full-bleed__figure.s-video-bg").find("video").attr("tabindex","0")},500)};d.prototype.eventFocusLock=function(a){a.keyCode===q.keyCode.TAB_KEY&&(!1===a.shiftKey&&this.ele.LayerPopup.find(e.close).target[0]===document.activeElement?(a.preventDefault(),this.ele.LayerPopup.focus()):!0===a.shiftKey&&this.ele.LayerPopup.target[0]===document.activeElement&&(a.preventDefault(),this.ele.close.focus()))};d.prototype.setVideoSize=
function(){if(!1!==this.isMobilePcDim&&null!==this.ele.LayerPopup&&"block"===this.ele.LayerPopup.target[0].style.display){var a=this.ele.LayerPopup.find(".st-feature-benefit-full-bleed__video-wrap, .st-feature-benefit-full-bleed__showroom-wrap").target[0];a.classList.contains("st-feature-benefit-full-bleed__showroom-wrap")?"desktop"===h.getCurrentDevice()?.9*window.innerHeight<8.1*window.innerWidth/16?(a.style.width=14.4*window.innerHeight/9+"px",a.style.height=.9*window.innerHeight+"px"):(a.style.width=
.9*window.innerWidth+"px",a.style.height=8.1*window.innerWidth/16+"px"):.9*window.innerWidth<7.2*window.innerHeight/16?(a.style.height=14.4*window.innerWidth/9+"px",a.style.width=.9*window.innerWidth+"px"):(a.style.height=.8*window.innerHeight+"px",a.style.width=7.2*window.innerHeight/16+"px"):this.ele.btn.hasClass("video-display--vertical")?.9*window.innerWidth<7.2*window.innerHeight/16?(a.style.height=14.4*window.innerWidth/9+"px",a.style.width=.9*window.innerWidth+"px"):(a.style.height=.8*window.innerHeight+
"px",a.style.width=7.2*window.innerHeight/16+"px"):"desktop"===h.getCurrentDevice()?.9*window.innerHeight<8.1*window.innerWidth/16?(a.style.width=14.4*window.innerHeight/9+"px",a.style.height=.9*window.innerHeight+"px"):(a.style.width=.9*window.innerWidth+"px",a.style.height=8.1*window.innerWidth/16+"px"):(a.style.width=window.innerWidth+"px",a.style.height=9*window.innerWidth/16+"px")}};d.prototype.openPopup=function(a){var b=this,c=!1===a.classList.contains("js-showroom");c?this.ele.LayerPopup=
this.ele.section.find(".st-feature-benefit-full-bleed__video-layer"):(this.ele.LayerPopup=this.ele.section.find(".st-feature-benefit-full-bleed__showroom-layer"),this.ele.LayerPopup.find("iframe").attr("src",a.dataset.href));this.ele.LayerPopup.css({display:"block"});this.ele.LayerPopup.attr("tabindex",0);c&&(l.init(this.ele.video),this.contentVideo&&this.ele.section.find(e.video).find(".video-player").target[0].pause());var d=this.ele.section.hasClass(e.layerTypeVideo)||!1===c;if(d||!(m.MOBILE<h.getViewPort().width))this.ele.window.off("keydown",
this.event.focusLock).on("keydown",this.event.focusLock);setTimeout(function(){b.ele.LayerPopup.attr("tabindex",0);b.ele.LayerPopup.find(".st-feature-benefit-full-bleed__close").focus();!0!==d?(b.isPc=null,m.MOBILE>=h.getViewPort().width?(n(b.ele.LayerPopup.target[0]),b.setMobileFocusLoop=!0,h.hiddenScroll()):b.ele.sectionInner.attr("aria-hidden",!0)):(!0!==b.setMobileFocusLoop&&(n(b.ele.LayerPopup.target[0]),b.setMobileFocusLoop=!0),h.hiddenScroll(),g(window).off("resize",b.handler.resize).on("resize",
b.handler.resize))},400);c&&"mp4"===this.ele.video.getAttribute("data-video-type")&&JSON.parse(this.ele.video.getAttribute("data-video-data")).controls&&g(this.ele.video).find("video").attr("tabindex","0");this.ele.btnWrap.find(".cta").attr("tabindex","-1");d&&this.handler.resize()};d.prototype.closePopup=function(){var a=this;this.ele.sectionInner.removeAttr("aria-hidden");this.ele.btnWrap.find(".cta").removeAttr("tabindex");this.ele.btnWrap.find(".cta").css({display:"inline-flex"});!0===this.setMobileFocusLoop&&
(r(),this.setMobileFocusLoop=!1);setTimeout(function(){a.ele.LayerPopup.hasClass("st-feature-benefit-full-bleed__video-wrap")?a.ele.section.find(".st-feature-benefit-full-bleed__cta .js-video-play").focus():a.ele.section.find(".js-showroom").focus();a.ele.LayerPopup.css({display:"none"});l.dispose(a.ele.video);a.contentVideo&&a.ele.section.find(e.video).find(".video-player").target[0].play();a.ele.LayerPopup.find(".st-feature-benefit-full-bleed__video-wrap, .st-feature-benefit-full-bleed__showroom-wrap").css({width:"",
height:""});a.ele.LayerPopup=null},200);this.ele.LayerPopup.attr("tabindex","");h.visibleScroll();g(window).off("resize",this.handler.resize)};d.prototype.init=function(){this.bindEvents()};d.prototype.reInit=function(){this.setProperty();this.bindEvents()};d.prototype.bindEvents=function(){var a=this;this.ele.btn.off("click").on("click",function(b){a.openPopup(b.currentTarget)});this.ele.close.off("click").on("click",function(){a.closePopup()});this.ele.ctaButton.target.forEach(function(b){g(b).off("click",
a.handler.clickCtaButton).on("click",a.handler.clickCtaButton)})};d.instances=new WeakMap;window.sg.components.featureBenefitFullBleed={init:c,reInit:function(a){a?k(a)&&f(a):(k(document),g(e.section).target.forEach(function(a){f(a)}))}};g.ready(c);g.load(c)})();